### ISSUE TITLE
Scrollbars on Memory Map

### ISSUE THREAD

**Issue by a-n-d-a-i** [mist64/c64ref#15]
Hi, currently you have to scroll all the way to the bottom of the page in order to scroll left and right, because the scrollbar is attached to a div instead of the body. 

Removing the overflow: scroll; property line (internal css, line 81) solves the issue.

div.disassembly_container_no_dec {
    padding: 1em 0em 1em 11.3em;
    overflow: scroll;
}

There is another in div.disassembly_container_with_dec. (line 76).

Hope this helps!

**Comment by mist64** [comment]
Interesting – which browser is that, where you have to scroll all the way to the bottom?

I tested it with the Firefox, Chromium and Safari on Mac, and scrolling with the pointer over the table will allow scrolling horizontally.

**Comment by a-n-d-a-i** [comment]
As you say, it is possible to scroll with a horizontal scroll (or with the arrow keys). But I cannot scroll with the scroll bar, without scrolling to the bottom of the page first (or removing overflow:scroll).
Because with the current CSS, the scroll bar is inaccessible and for all intents, unusable.

I do not have an input device that supports horizontal scrolling. My scroll wheel is a literal wheel and it only scrolls vertically. (This is the most common kind of input device on desktop computers, even today). Although Firefox and Chrome can emulate this (somewhat poorly) with middle click + drag.

I had a Mac too not long ago, and it was a very nice experience. But I do not have one now, and sadly neither do most people in the world.

Tested in Brave, Chrome and Firefox on Windows.

See also these 4 comments from the discussion on Hacker News: https://news.ycombinator.com/item?id=23203020

> There's no horizontal scrollbar for me on Safari, which kind of makes comparing different takes on each address impossible unless you have four monitors to stretch this across. Or Firefox or Chrome, now that I check it on them. (OSX 10.14.6, Safari 13.1, FF 76.0.1, Chrome 81.0.4044.13)

> Please let the BROWSER show the scroll-bars. Now it's fairly unusable.

> Going in the CSS and removing "overflow: scroll" from "div.disassembly_container_no_dec" makes it scroll horizonally and vertically properly.

> Whenever I find a site with good information but horrible readability, I turn off the CSS. That often makes it look bland, but it becomes far more readable --- more like a book. Some browsers have a "reader mode" which does a similar thing. Sometimes I may send the author an email about it.

**Comment by ellduin** [comment]
@avelican hi, this has been a long time in the making. would you mind checking out https://www.pagetable.com/c64ref/
(kernal, memory map or rom disassembly) and see if it behaves better for you?
