### ISSUE TITLE
Table rows vertically misaligned on Firefox

### ISSUE THREAD

**Issue by rhalkyard** [mist64/c64ref#20]
When viewing the Kernal API, ROM Disassembly, or Memory Map pages with Firefox, the Disassembly/Address row is about half a line further down than the commentary row that it corresponds to. This does not appear to happen in Chrome or IE. See the difference in the attached screenshots:

`Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:83.0) Gecko/20100101 Firefox/83.0`:
![image](https://user-images.githubusercontent.com/741060/101990609-68a9ea80-3c6d-11eb-83d3-424d2a903f4c.png)

`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36`:
![image](https://user-images.githubusercontent.com/741060/101990893-a8bd9d00-3c6e-11eb-9f1c-56b52c18ad00.png)

**Comment by brandonrobertz** [comment]
This appears to be related to a [20 year old Firefox rendering bug](https://bugzilla.mozilla.org/show_bug.cgi?id=63895), so I think a FF-specific hack would be required here. On my local, I just open devtools and put a small (-15px) `margin-top` on `.left-column` to fix it.

**Comment by ellduin** [comment]
hi @brandonrobertz @rhalkyard, this has been a long time in the making. would you mind checking out
https://www.pagetable.com/c64ref/
(kernal, memory map or rom disassembly)
and see if it behaves better for you?
