### ISSUE TITLE
PETSCII code 255 maps to wrong character

### ISSUE THREAD

**Issue by szabadulas** [mist64/c64ref#22]
The PETSCII code 255 should be the same character as code 126, but it erroneously maps to code 191 in your PETSCII table. (Perhaps the problem is around [here in generate.py](https://github.com/mist64/c64ref/blob/7924a6f717ce34b51c593986bd3faeb25104c7ab/charset/generate.py#L229).)

For reference:
![](https://i.imgur.com/VKoGL9w.png)

**Comment by ellduin** [comment]
@szabadulas thank you :)

<img width="1089" alt="Screenshot 2024-07-09 at 12 23 26" src="https://github.com/mist64/c64ref/assets/772311/a1972a80-ffca-477e-97d6-800603802911">

https://www.pagetable.com/c64ref/charset/
