### ISSUE TITLE
Missing [$nn],Y Addressing Mode

### ISSUE THREAD

**Issue by noyen1973** [mist64/c64ref#47]
The WDC 65C816 CPU instruction reference chart at https://www.pagetable.com/c64ref/6502/?cpu=65c816&tab=2 appears to be missing all of the Direct Page Indirect Long Y-Indexed addressing mode opcodes.

**Comment by ellduin** [comment]
<img width="451" alt="Screenshot 2024-07-09 at 13 34 58" src="https://github.com/mist64/c64ref/assets/772311/4b020a60-bf09-4b00-a565-f7d66d224149">

Thank you :) and there you go: 
https://www.pagetable.com/c64ref/6502/?cpu=65c816&tab=3#[a8],Y
