### ISSUE TITLE
SQRHLF

### ISSUE THREAD

**Issue by ExileInParadise** [mist64/c64ref#5]
The fully commented ROM for MS has the SQRHLF bytes starting at B9D5 which is $20.
The $20 at B9D5 is actually the 5th byte of the previous float 2.8853900728 in LOGCN2.
SQRHLF's 5 float bytes start at B9D6.

The incorrect listing is below for context:
.:B9D1 82 38 AA 3B 20                   202     ; 2.8853900728 <=== B9D1
                                        070 <=== B9D2
                                        252 <=== B9D3
                                        073 <=== B9D4
                                        040>  <=== is actually B9D5 20 (hex)
.:B9D5 80 35 04 F3 34           SQRHLF: 200     ; SQR(0.5) <=== SQRHLF starts at B9D6 80 (200octal)
                                        065
                                        004
                                        363
                                IFN     ADDPRC,<064>
.:B9DB 81 35 04 F3 34           SQRTWO: 201     ; SQR(2.0) <=== is crrect address and label

**Comment by mist64** [comment]
Fixed by 06a9cd28
